### ISSUE TITLE
[Question] How accurate are the test ?

### ISSUE THREAD

**Issue by yoobi** [bamlab/flashlight#124] opened 2023-06-20 19:32 UTC
Hello,

I've seen your video in AndroidMakers, it made me want to know more about flashlight and integrate it in my CI. I have a couple questions regarding the tests.
- If I have 2 devices (one is an emulator, the other is a real device) they have the same specifications in terms of RAM, CPU and android version. Will the result be the same ?
- If I were to add flashlight to my CI, should I use your cloud or create an emulator which will run the test ?

**Comment by Almouro** [comment] 2023-06-21 14:52
Hi @yoobi, 

2 great questions, thanks for asking!

- I doubt that you could reproduce the same results with a real device and emulator because I don't think you can 100% emulate the same CPU speed (but if so I'd be really keen to know though!)

- you can do whatever you prefer! 
  - We prefer running on real device on `flashlight cloud` (using AWS Device Farm) to give a result that would be close to the actual experience users are having
  - but you're free to run the `flashlight test` command on CI with an emulator (or even your own device farm)

**Comment by yoobi** [comment] 2023-06-21 15:46
Thanks for the info and the help :)

**Comment by Almouro** [comment] 2023-06-27 09:28
Hi @yoobi, doing a bit of cleanup on Github issues, so I'm closing this one for now. Feel free to reopen if anything is unclear! ☺️

**Closed by Almouro** 2023-06-27 09:28 UTC
Labels: question
