### ISSUE TITLE
Can't install flashlight on windows 11

### ISSUE THREAD

**Issue by Puetz** [bamlab/flashlight#82] opened 2023-03-30 14:08 UTC
Hello, 

since the [Flipper plugin is not working on Windows](https://github.com/bamlab/flashlight/issues/76) I tried to install the CLI.
When I run `curl https://get.flashlight.dev/ | bash` in the regular command prompt i'm getting an error saying  
"OS MINGW64_NT-10.0-22621 is not supported."  

When I run it in Power Shell I'm getting a bunch of "command not found" errors.  
I opened both, Powershell and CMD, as administrator. 

![image](https://user-images.githubusercontent.com/34755160/228862756-f0eb74f6-66f1-4393-a04b-25a199931472.png)

Did I do something wrong or is there simply no way to use flashlight on Windows?

**Comment by Almouro** [comment] 2023-03-30 16:18
Hi @Puetz, you didn't do anything wrong, turns out that Flashlight needs a few fixes to make it work with Windows properly 🙈

https://github.com/bamlab/flashlight/pull/77 is the PR to fix it (both CLI and Flipper), should land next week! 🤞

**Comment by Almouro** [comment] 2023-07-03 12:12
We also have a proper installer now for Windows, documented in https://docs.flashlight.dev/ so I'm closing this one!
Feel free to reopen @Puetz if the issue is not fixed!

**Closed by Almouro** 2023-07-03 12:12 UTC
Labels: bug
